/** The Hono application — the oRPC handler and every plain route are mounted here. */

import { RPCHandler } from "@orpc/server/fetch";
import { Hono } from "hono";
import { router } from "@/rpc/router";
import { createDatabase } from "@/utilities/database-service";

// The handler is stateless and holds no config, so building it once per isolate
// is correct — the per-request values go in `context` below, never in here.
const rpc = new RPCHandler(router);

/**
 * The assembled app. `index.ts` exports it as the Worker's fetch handler; tests
 * drive it through the real runtime with `exports.default.fetch(...)`. Keep this
 * file to wiring — no business logic.
 *
 * `Bindings: Env` types `c.env`, so every binding, var and secret declared in
 * `wrangler.jsonc` is checked at the call site. `Env` comes from
 * `worker-configuration.d.ts`, regenerated by `bun run cf-typegen` — rerun it
 * whenever you add a binding, or `c.env.NEW_THING` is a type error.
 */
export const app = new Hono<{ Bindings: Env }>();

// Liveness probe — returns 200 while the Worker is serving. Plain routes like
// this one, webhooks, and auth callbacks stay in src/routes/; everything the
// product's own clients call goes through oRPC.
app.get("/health", (c) => c.json({ status: "ok" }));

app.get("/database/health", async (c) => {
  await (await createDatabase().prepare("select 1")).get();
  return c.json({ status: "ok" });
});

// The typed API surface. Everything under /rpc is an oRPC procedure from
// src/rpc/router.ts, validated in and out by its Zod schemas. `matched` is false
// when the path is not a procedure — fall through to a real 404 rather than
// returning an empty 200.
app.all("/rpc/*", async (c) => {
  const { matched, response } = await rpc.handle(c.req.raw, {
    prefix: "/rpc",
    context: { env: c.env, headers: c.req.raw.headers },
  });

  return matched ? response : c.notFound();
});
